a = 5 # penjumlahan 
b = 6 # pengurangan
c = 8 # perkalian 
d = 4 # pembagian 
e = 16 # modulus 
f = 2 # pangkat

a += 3
print("penjumlahan a =", a)
b -= 8
print("pemgurangan b =", b)
c *= 9
print("perkalian c=", c)
d /=6
print("pembagian d=", d)
e %= 2
print("moduluse e=", e)
f **=1
print("pangkat f=", f)